version=0.17.8

jacksonVersion=2.16.2
micronautVersion=4.4.3
lombokVersion=1.18.32
slf4jVersion=2.0.13

org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.jvmargs=-Xmx6g -Xms2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true

systemProp.http.proxyHost=kunden-proxy.rz.bankenit.de
systemProp.http.proxyPort=8080
systemProp.http.proxyUser=yf1v920
systemProp.http.proxyPassword=cast1dib

systemProp.https.proxyHost=kunden-proxy.rz.bankenit.de
systemProp.https.proxyPort=8080
systemProp.https.proxyUser=yf1v920
systemProp.https.proxyPassword=cast1dib

# Important for authentication
systemProp.jdk.http.auth.tunneling.disabledSchemes=
systemProp.jdk.http.auth.proxying.disabledSchemes=