import org.siouan.frontendgradleplugin.infrastructure.gradle.RunNpm

plugins {
    id 'org.siouan.frontend-jdk11'
}

publishSonatypePublicationPublicationToSonatypeRepository.enabled = false

frontend {
    nodeVersion = '18.18.0'
    installScript = 'install'
    assembleScript = 'run build'
    checkScript = 'run test:unit'
    maxDownloadAttempts = 5

    httpProxyHost = System.getProperty("http.proxyHost")
    httpProxyPort = System.getProperty("http.proxyPort")?.toInteger()
    httpProxyUsername = System.getenv("PROXY_USER") ?: System.getProperty("http.proxyUser")
    httpProxyPassword = System.getenv("PROXY_PASSWORD") ?: System.getProperty("http.proxyPassword")

    httpsProxyHost = System.getProperty("http.proxyHost")
    httpsProxyPort = System.getProperty("http.proxyPort")?.toInteger()
    httpsProxyUsername = System.getenv("PROXY_USER") ?: System.getProperty("http.proxyUser")
    httpsProxyPassword = System.getenv("PROXY_PASSWORD") ?: System.getProperty("http.proxyPassword")
}

tasks.named('installFrontend') {
    inputs.files('package.json', 'package-lock.json')
    outputs.dir('node_modules')
}

tasks.named('assembleFrontend') {
    shouldRunAfter installFrontend

    inputs.dir('src')
    inputs.dir('public')
    inputs.files('vite.config.js')
    outputs.dir('../webserver/src/main/resources/ui')
}

final linterTask = tasks.register('lintFrontend', RunNpm) {
    dependsOn tasks.named('installFrontend')
    group 'Frontend'
    description 'Lints the frontend source code.'

    script = 'run test:lint'
}

check.dependsOn linterTask